### ISSUE TITLE
Про фигуры

### ISSUE THREAD

**Issue by sov-87** [Sunshine747/geometry#1]
Пока фигура должна быть достаточно пассивной и ничего не должна считать про себя. Только хранить самую необходимую информацию.

Для строкового представления фигуры будем использовать переопределение метода `toString()`. По-умолчанию в него входит имя (если задано поле name, то используется оно, если не задано, то надо брать имя класса), координаты для точки, координаты концов для отрезка и координаты вершин для многоугольника.

Вывод на экран будет таким: 
```
<цикл по фигурам>
  System.out.println(figure);
<все цикл по фигурам>
```

**Comment by Sunshine747** [comment]
done
