### ISSUE TITLE
Поменять получение имени

### ISSUE THREAD

**Issue by sov-87** [Sunshine747/geometry#4]
Сейчас если нет имени, то будет выдана пустота, это нехорошо. Если имя не задано, то должно выдаваться имя класса.
Это можно сделать в конструкторе фигуры - если не передано значение для имени, то заполнять его именем текущего класса.
Можно в методе `getName()` проверять поле `name` и выдавать имя класса, если оно пустое.

**Comment by Sunshine747** [comment]
Closed;
